### ISSUE TITLE
百度贴吧客户端无法登录

### ISSUE THREAD

**Issue by 948171624** [vokins/simpleu#6]
最新hosts的mobile.txt使用后无法登录贴吧客户端，之前没事，禁用一切正常。

**Comment by vokins** [comment]
抱歉，一直没看这个issue，今天修正了贴吧头像的问题，你再试试呢？

**Comment by 948171624** [comment]
谢谢，新版正常工作

**Comment by vokins** [comment]
好的，有问题可以再说。感谢反馈。
